### ISSUE TITLE
login stopped working

### ISSUE THREAD

**Issue by jedbowser** [Protocol-X/plugin.video.funimationnow#6]
I was using the addon a couple of weeks ago or more and while I finished an episode and tried to start the next I got some error and was logged out and it lost all settimgs and log in setting and when I put them back in it never logs in. I'm using a generic build of libreelec beta. I tried everything I could think of. Even doing a clean install. I also tried it on a wetek core with libreelec official release and can't get the login to work. I can only get the free first couple of episodes. Not any of the content my account would give me.

**Comment by jedbowser** [comment]
Might not be your addon. My android app can't log in either, but ps4 can and the website works.

**Comment by Protocol-X** [comment]
Hi Jeff, sorry for the troubles.  But I just tested and it works fine for me.  The Android app uses a different api so the fact that it does not work might be a different issue.   Do you see "my anime / queue" or "log in". On the main funimation now screen on your pi?  Also when you tried a clean install did you go in and delete the appdata folder for funimation now?  http://kodi.wiki/view/userdata   Sometimes it does not delete.  I recall am issue once with corrupt data causing a similar issue.   What country are you in?

**Comment by Protocol-X** [comment]
Also do you have any profiles set up and or are using?

**Comment by jedbowser** [comment]
Still can't get it to work for either. I did a fresh install of generic libreelec on my pc and made sure there was no files left anywhere. The only addon I got on it right now is Funimationnow. It has "Login" no "my anime /queue". I am in Canada.

**Comment by Protocol-X** [comment]
Do you have any errors in your kodi logs?

On Dec 24, 2016 5:03 PM, "jedbowser" <notifications@github.com> wrote:

Still can't get it to work for either. I did a fresh install of generic
libreelec on my pc and made sure there was no files left anywhere. The only
addon I got on it right now is Funimationnow. It has "Login" no "my anime
/queue". I am in Canada.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Protocol-X/plugin.video.funimationnow/issues/6#issuecomment-269102077>,
or mute the thread

**Comment by jedbowser** [comment]
There are some errors
21:49:36 T:139956357375744 ERROR: CCurlFile::FillBuffer - Failed: Couldn't resolve host name(6) 21:49:36 T:139956357375744 ERROR: CCurlFile::Open failed with code 0 for http://mirrors.kodi.tv/addons/jarvis/addons.xml.gz.md5 21:49:36 T:139956357375744 ERROR: Open - failed to open source <http://mirrors.kodi.tv/addons/jarvis/addons.xml.gz.md5> 21:49:36 T:139956357375744 ERROR: CRepositoryUpdateJob[repository.xbmc.org] failed read checksum for directory 'http://mirrors.kodi.tv/addons/jarvis/addons.xml.gz' 21:49:36 T:139956739336256 NOTICE: starting zeroconf publishing 21:49:36 T:139956739336256 NOTICE: WebServer: Started the webserver 21:49:36 T:139956739336256 NOTICE: starting upnp client 21:49:36 T:139955938522880 NOTICE: ES: Starting UDP Event server on 127.0.0.1:9777 21:49:36 T:139955938522880 NOTICE: UDP: Listening on port 9777 21:49:36 T:139956357375744 ERROR: CCurlFile::FillBuffer - Failed: Couldn't resolve host name(6) 21:49:36 T:139956357375744 ERROR: CCurlFile::Open failed with code 0 for http://addons.libreelec.tv/7.0/Generic/x86_64/addons.xml.gz.md5 21:49:36 T:139956357375744 ERROR: Open - failed to open source <http://addons.libreelec.tv/7.0/Generic/x86_64/addons.xml.gz.md5> 21:49:36 T:139956357375744 ERROR: CRepositoryUpdateJob[repository.libreelec.tv] failed read checksum for directory 'http://addons.libreelec.tv/7.0/Generic/x86_64/addons.xml.gz' 21:49:36 T:139956374161152 NOTICE: ## LibreELEC Addon ## 0.7.3 21:49:36 T:139956374161152 WARNING: CSkinInfo: failed to load skin settings 21:49:37 T:139956739336256 WARNING: Previous line repeats 1 times. 21:49:37 T:139956739336256 ERROR: Control 1500 in window 13001 has been asked to focus, but it can't 21:50:38 T:139955460368128 ERROR: Previous line repeats 1 times. 21:50:38 T:139955460368128 WARNING: CSkinInfo: failed to load skin settings 21:55:59 T:139956739336256 ERROR: GetDirectory - Error getting plugin://plugin.video.funimationnow/?action=loginNavigator 21:55:59 T:139956739336256 ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.funimationnow/?action=loginNavigator) failed 22:17:50 T:139955921737472 WARNING: CSkinInfo: failed to load skin settings 22:17:51 T:139956739336256 ERROR: Control 1000 in window 13001 has been asked to focus, but it can't 22:18:00 T:139955921737472 NOTICE: ####dbus.Boolean(True, variant_level=1) 22:18:44 T:139956739336256 ERROR: Unable to activate the previous window

**Comment by jedbowser** [comment]
I've also tried the add on on a Windows pc with kodi installed from the windows store and it does the same thing. Just doesn't log in. Ive checked its logs and there is no errors there.

**Comment by Protocol-X** [comment]
What happens when you login nothing? An error?  I see it Is showing an
error even trying to get to the lol login page

**Comment by jedbowser** [comment]
It just says working for a second and nothing happens.

**Comment by Protocol-X** [comment]
If you go to settings does it provide your subscription level?

**Comment by jedbowser** [comment]
It says Non-Subscriber and Unregistered

**Comment by Protocol-X** [comment]
You are using your user name and not an email correct?

**Comment by jedbowser** [comment]
I use and email.

**Comment by Protocol-X** [comment]
Email only works for the Android app. Ps4 and kodi need a userid.   The api
has not been converted yet

**Comment by Protocol-X** [comment]
Ive been working on the new api but it will be a while until it is ready

**Comment by jedbowser** [comment]
I was using an email before with no problems. Anyway I tried what the funimation site says my user name is and it also doesn't work. Oh well guess I'll be using my ps4 for it again. Sad cuz your app has a way better interface. Anyways thanks for trying to help.

**Comment by Protocol-X** [comment]
Weird. Email has never worked for me. I should have the new version soon it
is mainly done, just fixing bugs

On Dec 24, 2016 6:30 PM, "jedbowser" <notifications@github.com> wrote:

I was using an email before with no problems. Anyway I tried what the
funimation site says my user name is and it also doesn't work. Oh well
guess I'll be using my ps4 for it again. Sad cuz your app has a way better
interface. Anyways thanks for trying to help.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Protocol-X/plugin.video.funimationnow/issues/6#issuecomment-269104119>,
or mute the thread

**Comment by gitmatt19** [comment]
HI 
I have been using the old funimation addon for the last year or so and now I have seen yours which looks better, but I have two problems using it.
1) it does not look like I am actually getting logged in (same user/email/pass as the old addon)
2) the bit rate at SD480 is different on your addon than on the old addon so buffers alot on me. Not sure this might not be related to issue #1

**Comment by Protocol-X** [comment]
The old api only allows userid not email .  For me at least. 

The framrates are the same. Can you tell me what device you have it installed on as well as kodi versions?

**Comment by gitmatt19** [comment]
I have the 6.95 openelec, I think that is Kodi 16.1

I tried email and login both seem the same. here are some error I just saw :+1: 
17:05:52 T:139980205631552   ERROR: GetDirectory - Error getting plugin://plugin.video.funimationnow/?action=loginNavigator
17:05:52 T:139980205631552   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.funimationnow/?action=loginNavigator) failed
17:06:12 T:139979611166464   ERROR: [plugin.video.funimationnow] fetch : no such table: cookies
17:06:18 T:139979611166464   ERROR: Previous line repeats 1 times.
17:06:18 T:139979611166464   ERROR: [plugin.video.funimationnow] fetchfnmetacheck : [(u'2017-01-08 15:38:31.477480',)]
17:06:18 T:139979611166464   ERROR: [plugin.video.funimationnow] fetchfnhistorycheck : [(u'2017-01-08 15:38:33.158189',)]

thanks

**Comment by Protocol-X** [comment]
From those errors it looks like the addon does not have permission to write to the db files.  Are you using profiles or the default? 

There should be folders in the app_data/pluginname folder

**Comment by gitmatt19** [comment]
here is what I see :
 ls -l /storage/.kodi/userdata/addon_data/plugin.video.funimationnow
total 76
-rw-r--r--    1 root     root         12288 Jan  7 16:32 cache.db
-rw-r--r--    1 root     root             0 Jan  7 15:38 cookies.db
-rw-r--r--    1 root     root          1271 Jan  7 17:24 settings.xml
-rw-r--r--    1 root     root         53248 Jan  7 16:32 synch.db
-rw-r--r--    1 root     root          8192 Jan  7 15:38 tokens.db

**Comment by Protocol-X** [comment]
Can you delete those db's as well as the settings.xml file and try again?  Maybe something got corrupted

**Comment by Protocol-X** [comment]
Also if it still fails, please include the contents of settings.xml

**Comment by Protocol-X** [comment]
After you remove your password from it please

**Comment by gitmatt19** [comment]
I found the issue... Its funimation, they let their SSL cert expire and the new OPENELEC uses the new python which now does strict certificate checking so fails on the SSL connection because it cannot verify the SSL cert is valid...

/storage/.kodi/addons/plugin.video.funimationnow/resources/lib/modules/utils.py

url = 'https://www.funimation.com/feeds/ps/login.json?v=2';

I did a test just now and made it http instead if https and it worked and logged in fine.

The best solution is for funimation to fix their @#@# cert, letting it expire is poor...

**Comment by Protocol-X** [comment]
Awesome.   They probably won't renew it though.  They are trying to migrate to the new API.   I'm almost complete with the new api so hopefully it will be out soon.

**Comment by Protocol-X** [comment]
@jedbowser are you around?

**Comment by jedbowser** [comment]
I am here. Not. Shore what everything that has been said means. Or what file I would need to edit.

**Comment by Protocol-X** [comment]
Basically try changing the url from https to http.

kodi/addons/plugin.video.funimationnow/resources/lib/modules/utils.py

url = 'http://www.funimation.com/feeds/ps/login.json?v=2
<https://www.funimation.com/feeds/ps/login.json?v=2>';

**Comment by jedbowser** [comment]
Worked. Thank you very much 😎

**Comment by Protocol-X** [comment]
Thanks @gitmatt19 for finding to root of that issue,  thanks for your patience @jedbowser.
