### ISSUE TITLE
video bitrate differences at SD480 between old funimation addon and new one

### ISSUE THREAD

**Issue by gitmatt19** [Protocol-X/plugin.video.funimationnow#7]
for some reason there is a video bitrate difference between the old funimation addon and the new one at SD480.

It is just enough to cause a 1.5mbit DSL line to buffer a lot in the new addon. Below are images showing the first ~minute of episode 1 of assassination classroom played on both addons. The old addon buffer once when it starts and then plays ok. The new addon buffer 4 times for the same amount of video. Not sure what the difference is there, but a lower bitrate like the old addon would be good because they would let you buffer up a few minutes to level out the video. 

![newfunimationaddon](https://cloud.githubusercontent.com/assets/17283802/21746820/bac569d8-d507-11e6-8d84-def6ac36f229.png)
![oldfunimationaddon](https://cloud.githubusercontent.com/assets/17283802/21746822/bcf5d0c6-d507-11e6-96b2-465743a93032.png)

**Comment by Protocol-X** [comment]
This is a newer video which probably supports 480 & 540.  The plugin are near identical for choosing bitrate.  If you look modules directory you can see the code for selecting playback rate.

**Comment by gitmatt19** [comment]
I see this which explains it... 2 different bitrates...

Old addon :
18:43:37 T:140646473463872  NOTICE: DVDPlayer: Opening: http  ://wpc.8c48.edgecastcdn.net/038C48/SV/480/ASSENG0001/ASSENG0001-480-**750K**.mp4.m3u8

New Addon :
18:46:18 T:140646473463872  NOTICE: DVDPlayer: Opening: http  ://wpc.8c48.edgecastcdn.net/038C48/SV/480/ASSENG0001/ASSENG0001-480-**1500K**.mp4.m3u8?

Can we get an option for the lower bit rate for us bandwidth impaired people ?

thanks

Matt

**Comment by Protocol-X** [comment]
Yes his plays the lowest 480 br mine plays the highest. You can edit it in the animexxx.py file in the modules directory. My new addon will have a slider to choose instead of 3 options but to update this my self it takes about a month for them to update the repo with a pull request

**Comment by Protocol-X** [comment]
Change the 1500 to 750

https://github.com/Protocol-X/plugin.video.funimationnow/blob/master/resources/lib/indexers/animeshows.py


qdict = {
            0:1500, 
            1:2500, 
            2:4000
        };

        hedict = {
            750:[640, 480],
            #1500:[768, 576], # aert by year
            1500:[960, 540],
            2000:[1280, 720],
            2500:[1280, 720],
            4000:[1920, 1080],
        };

**Comment by gitmatt19** [comment]
thanks !

works

I had to change it in utils.py also.

**Comment by Protocol-X** [comment]
Ah sorry.  I forgot. This was my first addon so it's kind of a mess

**Comment by Protocol-X** [comment]
@gitmatt19 Want to test this out?
https://github.com/Protocol-X/script.video.funimationnow

**Comment by gitmatt19** [comment]
I will try to take a look this weekend.

Matt

**Comment by Protocol-X** [comment]
You may want to open settings prior and reduce the video quality and image quality and maybe even disable the background data synch or you can try without and if it is to slow then make the changes
